---
name: Pull Request CI

on:
  pull_request:
    branches:
      - main
      - master

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: false

env:
  CHANGELOG_COMMIT_MESSAGE: "docs(bot): Updated CHANGELOG"
  NODE_VERSION: 20.x

jobs:
  lint:
    runs-on: ubuntu-latest
    if: (!contains(toJSON(github.event.head_commit.message), '(bot)'))
    steps:
      - uses: actions/checkout@v3.4.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - run: echo 'No FVTT tests yet...'
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [test]
    steps:
      - uses: actions/checkout@v3.4.0
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          echo \
          "# ${{ github.event.pull_request.title }}

          $(git log --pretty=%s ${{ github.event.pull_request.base.sha }}..HEAD | grep -v '${{ env.CHANGELOG_COMMIT_MESSAGE }}' | tac)
          " > "CHANGELOG.d/${{ github.event.pull_request.title }}.md"

          echo -n > "CHANGELOG.md" && find "CHANGELOG.d/" -type f -name "*.md" | sort -r | xargs -I {} cat {} >> CHANGELOG.md
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.head.ref }}
          commit_message: ${{ env.CHANGELOG_COMMIT_MESSAGE }}
          file_pattern: CHANGELOG\.md CHANGELOG\.d/*
